Vagrant.configure("2") do |config|

    config.vm.define "cicd" do |cicd|
        cicd.vm.box = "ubuntu/xenial64"
        cicd.vm.hostname = "cicd"
    end

    config.vm.define "server" do |server|
        server.vm.box = "ubuntu/xenial64"
        server.vm.hostname = "dev"
    end

end
